### ISSUE TITLE
Accessibility improvement

### ISSUE THREAD

**Issue by feimosi** [JamieLivingstone/TheJSQuiz#1]
You should bind `onClick` to `<button>` rather that to `<span>`. It's not only good for a11y but also convenient for people using keyboard shortcuts e.g. with [Vimium](https://chrome.google.com/webstore/detail/vimium/dbepggeogbaibhgnhhndojpepiihcmeb).

Anyway, nice quiz 👍

**Comment by JamieLivingstone** [comment]
Hi, thank you for pointing that out I will get that changed when I get home this evening :) good spot! I will also be adding allot more questions when I get time as well to improve it

**Comment by feimosi** [comment]
Great, keep going!
