### ISSUE TITLE
Math.PI in advanced quizz

### ISSUE THREAD

**Issue by ymainier** [JamieLivingstone/TheJSQuiz#2]
Hello,

I noticed a typo in the question "Math.Pi returns the mathematical constant of Pi. What standard JavaScript method would truncate Math.Pi to 3.14 ?" : It is Math.PI (upper case)

Thanks for the great resource !

**Comment by JamieLivingstone** [comment]
Hi ymainier,

Thank you for informing me, I have updated that :)

And your welcome!
