### ISSUE TITLE
Doesn't count correct statistics at the end of tests

### ISSUE THREAD

**Issue by alexd3d** [JamieLivingstone/TheJSQuiz#3]
Hi and Thanks for the app! :)
But it has a small issue - if you click multiple times at wrong answers in one test task - it will count as mistakes. And at the end of a test you can see something like this: "Correct answers: 14, incorrect answers: 15." But total number of tasks is 15... I think I got your idea if it was intentionally counted but in this case final statistics messages should be rephrased or something as it's too confusing right now. Thanks!

**Comment by JamieLivingstone** [comment]
Hi, your more than welcome :)

I completely agree with you on this, when I get some time later this evening or in the morning I will get that rephrased as it's sure as hell confusing even for me!

**Comment by alexd3d** [comment]
There's another great feature you can add to your app if you find it useful - store all final results at different levels and then show the user something like "[Great!] You have answered better than [78]% of all who passed this test" (same approach as they use on https://learn.javascript.ru/quiz/js-basic). I find this phrase quite meaningful and more personalized as you feels connection and comparision to others who passed the same test. So it will help to evaluate oneself better.

**Comment by JamieLivingstone** [comment]
Funnily enough this feature is already half built, I have done it in a slightly different way though. At the end of the quiz you will be able to sign in with GitHub and add your score to the leaderboards. Before I finish the feature I need to add some more questions to the quiz so it's more random and difficult.

Hopefully once I have added the feature it will make the quiz much more fun and competitive to try and get to the top of the leaderboard.
