### ISSUE TITLE
Weird quotes are very confusing

### ISSUE THREAD

**Issue by CosmoMyzrailGorynych** [JamieLivingstone/TheJSQuiz#4]
If you are a bit experienced in JS and able to distinguish curly and straight quotation marks, you will quickly hit a `SyntaxError` there, because curly quotes are illegal characters in js and **definitely not the same characters as "dumb" quotes** >:| 

![image](https://cloud.githubusercontent.com/assets/3174357/25528215/c1a3437c-2c70-11e7-93ff-c99c7ae689b0.png)

It really made me feel angry and cheated because you start with correct quotes first and then suddenly switch to typographic ones. 
- - -
![image](https://cloud.githubusercontent.com/assets/3174357/25528547/7e6e149a-2c72-11e7-84e2-d9b15127a75f.png)
- - -
![image](https://cloud.githubusercontent.com/assets/3174357/25528567/9e34d93a-2c72-11e7-9231-cf720c414d69.png)

**Comment by JamieLivingstone** [comment]
Fixed, thanks for pointing that out!
